//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryType
    {
        public int ID { get; set; }
        public int CategoryId { get; set; }
        public int ServiceTypeId { get; set; }
    
        public virtual ProviderServiceCategory ProviderServiceCategory { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
