//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public ContactPerson()
        {
            this.Locations = new HashSet<Location>();
        }
    
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public Nullable<int> ContactID { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
