//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public Contact()
        {
            this.ContactPersons = new HashSet<ContactPerson>();
            this.CrisisContacts = new HashSet<CrisisContact>();
            this.Locations = new HashSet<Location>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string HelpLine { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        public virtual ICollection<CrisisContact> CrisisContacts { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
