//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class County
    {
        public County()
        {
            this.ProviderCoverages = new HashSet<ProviderCoverage>();
        }
    
        public int ID { get; set; }
        public int StateId { get; set; }
        public string Name { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<ProviderCoverage> ProviderCoverages { get; set; }
    }
}
