//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invite
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string Token { get; set; }
        public int RoleTypeID { get; set; }
        public Nullable<int> ProviderId { get; set; }
    
        public virtual User User { get; set; }
        public virtual RoleType RoleType { get; set; }
    }
}
