//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.CategoryTypes = new HashSet<CategoryType>();
            this.ServiceProviders = new HashSet<ServiceProvider>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<CategoryType> CategoryTypes { get; set; }
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
    }
}
