//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProviderEdit
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string Action { get; set; }
        public string DeletedProviderName { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
    }
}
