//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.Counties = new HashSet<County>();
            this.Locations = new HashSet<Location>();
        }
    
        public int ID { get; set; }
        public string FullName { get; set; }
        public string Abbreviation { get; set; }
        public int CountryID { get; set; }
    
        public virtual ICollection<County> Counties { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<Location> Locations { get; set; }
    }
}
