//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tool
    {
        public int ID { get; set; }
        public string Website { get; set; }
        public string AppleStoreWebsite { get; set; }
        public string GooglePlayWebsite { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
    }
}
