//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry_Helpers
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Invites = new HashSet<Invite>();
            this.ServiceProviderEdits = new HashSet<ServiceProviderEdit>();
            this.UserRoles = new HashSet<UserRole>();
        }
    
        public int ID { get; set; }
        public int ContactID { get; set; }
        public int CredentialID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> PrimaryProviderCategoryID { get; set; }
        public Nullable<int> ServiceProviderID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ICollection<ServiceProviderEdit> ServiceProviderEdits { get; set; }
        public virtual UserCredential UserCredential { get; set; }
        public virtual ICollection<UserRole> UserRoles { get; set; }
    }
}
